### ISSUE TITLE
Please add release tags

### ISSUE THREAD

**Issue by tillea** [rlabduke/probe#4]
Hi,
I'm packaging probe for Debian.  To do so it would help to know what code you consider a release that is considered for the end user.  So it would help if you would tag the releases to mark the distributable code.
Thanks for considering, Andreas.

**Comment by tillea** [comment]
Hi again,
according to probe.c the version is

    static char *shortVersionStr = "probe.2.16.160404";

but development has moved on.  In Debian we are now using commit 9b198c1 from 20200121.  Some official release would be helpful.  If you consider doing some release I'd recommend inspecting the [patches](https://salsa.debian.org/med-team/king-probe/-/tree/master/debian/patches) we are using in Debian.
Kind regards, Andreas.

**Comment by russell-taylor** [comment]
I've added a version 2.18 release.  Development on this project is transitioning to Probe2 in the CCTBX: https://github.com/cctbx/cctbx_project

**Comment by tillea** [comment]
> I've added a version 2.18 release. Development on this project is transitioning to Probe2 in the CCTBX: https://github.com/cctbx/cctbx_project

Thanks for the pointer.  I realised that there is an old packaging attempt and I refreshed this packaging code in our development git but I do not feel competent enough in this specific field of science to finalise this.  I'll ping the people who started that attempt, thought.
